### ISSUE TITLE
ln function not working 

### ISSUE THREAD

**Issue by Sanjit1** [desmosinc/mathograms#10]
When I use an Equation with the ln function, it gives an error, in the expressions list and asks me to add sliders for l and n. I can fix it, by clicking on the equation and then pressing the left or right key. However I want to hide the expression list, for a much larger view of the graph, so this is becoming a problem.

Here is some code, so that you can see what is happening:

`var equation ='x=1/(A+(B*\ln(y))+(C*\ln(y)^3))-273.15';`
    `calculator.setExpressions([`
        `{id:'curve', latex:equation ,color: Desmos.Colors.GREEN},`
        `{id:'A', latex: 'A = '+ Adsn ,color: Desmos.Colors.BLUE},`
        `{id:'B', latex: 'B = '+ Bdsn ,color: Desmos.Colors.BLUE},`
        `{id:'C', latex: 'C = '+ Cdsn ,color: Desmos.Colors.BLUE},`
    `]);`

Before I press a key.

![image](https://user-images.githubusercontent.com/26168871/60404331-ccfdea80-9b5c-11e9-8f59-cb253af355a8.png)

and after I press a key in the equation:

![image](https://user-images.githubusercontent.com/26168871/60404348-f585e480-9b5c-11e9-80a9-d3cd92c2594e.png)

The reason why I cannot have the users make that change is that I want them to see the graph without the expressions:
`var calculator = Desmos.GraphingCalculator(elt,{expressions:true});`

**Comment by ctlusto** [comment]
If you want to use a LaTeX command that includes a backslash, you need to make sure we actually get the backslash. The string `'\ln'` is the same as the string `'ln'` in JavaScript, because `'\l'` is just `'l'`. If you want the backslash to show up in the string, you need to escape it: `'\\ln'` will evaluate to `'\ln'`.
